ARG IMAGE_TAG="ubuntu:noble"
FROM ${IMAGE_TAG}

# Copy custom codes and templates, update ENV for ready access
ARG  CUSTOM_DIR_SRC='../image_customizations'
ARG  CUSTOM_DIR_DST="/shadowbox"

# Within the container, where to install apps like Conda, etc.
ARG  APP_INSTALL_DIR="/usr/bin"
COPY "${CUSTOM_DIR_SRC}" "${CUSTOM_DIR_DST}"
ENV  PYTHONPATH="${CUSTOM_DIR_DST}/code/"

# Install essential CLI tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential ca-certificates \
        wget curl \
        nano vim less bat\
        libglib2.0-0 software-properties-common \
        procps tree htop tmux\
        zip bzip2 unzip xz-utils \ 
        iputils-ping net-tools \
        openssh-server ssh-client \
        fuse \
        git \
        sudo -y && \
    apt-get clean

# Install Bash customization themes
RUN     ln -s batcat /usr/bin/bat &&\
        curl -k -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/bin -t "${CUSTOM_DIR_DST}/omp_themes" &&\
        echo "########## Customization for Oh-My-Posh Bash themes ##########" >> ~/.bashrc &&\
        echo "eval \"\$(oh-my-posh init bash --config ${CUSTOM_DIR_DST}/omp_themes/sbp_clean_detailed.omp.json)\"" >> ~/.bashrc

# # Anaconda installation and initialization
# # Use exact Miniconda version
# RUN     MINICONDA_FILE=Miniconda3-latest-Linux-x86_64.sh &&\
#         wget --no-check-certificate https://repo.anaconda.com/miniconda/$MINICONDA_FILE  &&\
#         chmod 755 $MINICONDA_FILE &&\
#         ./$MINICONDA_FILE -p $APP_INSTALL_DIR/miniconda3 -b &&\
#         rm $MINICONDA_FILE &&\
#         ln -s $APP_INSTALL_DIR/miniconda3/bin/conda /$APP_INSTALL_DIR/conda &&\
#         conda init
        
# # ENV     CONDA_PREFIX="$HOME/miniconda3" PATH=$CONDA_PREFIX/bin/:$PATH

# # UPDATE 27th December 2023: Below lines break apt-get! Commenting but retaining if required for future
# # # Some customization required for TensorFlow conda installation
# # # For some reason, CONDA_PREFIX does not expand! So using HOME as expansion
# RUN     mkdir -p $HOME/miniconda3/etc/conda/activate.d &&\
#         echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/miniconda3/lib/' > $HOME/miniconda3/etc/conda/activate.d/env_vars.sh

# # # Install conda environments for each .yml file in the conda_envs directory, then clean up in single layer
# RUN     chmod +x "${custom_dir}/scripts/install_conda_envs.sh" &&\
#         ${custom_dir}/scripts/install_conda_envs.sh ${custom_dir}/conda_envs $HOME/miniconda3/bin/conda &&\
#         # Clean up all conda and pip mess
#         $HOME/miniconda3/bin/conda clean -a -y &&\
#         $HOME/miniconda3/bin/pip cache purge

# # Install Azure CLI
# RUN     curl -sL https://aka.ms/InstallAzureCLIDeb | bash &&\
#         az extension add -n ml -y
